# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'compareUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CompareDialog(object):
    def setupUi(self, CompareDialog):
        CompareDialog.setObjectName("CompareDialog")
        CompareDialog.resize(900, 600)
        self.verticalLayoutWidget = QtWidgets.QWidget(CompareDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 871, 90))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vlayout1_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vlayout1_2.setContentsMargins(0, 0, 0, 0)
        self.vlayout1_2.setObjectName("vlayout1_2")
        self.hlayout_3 = QtWidgets.QHBoxLayout()
        self.hlayout_3.setSpacing(200)
        self.hlayout_3.setObjectName("hlayout_3")
        self.hlayout1_3 = QtWidgets.QHBoxLayout()
        self.hlayout1_3.setSpacing(6)
        self.hlayout1_3.setObjectName("hlayout1_3")
        self.lb1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb1.setObjectName("lb1")
        self.hlayout1_3.addWidget(self.lb1)
        self.cbx1 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cbx1.setObjectName("cbx1")
        self.cbx1.addItem("")
        self.cbx1.addItem("")
        self.cbx1.addItem("")
        self.cbx1.addItem("")
        self.cbx1.addItem("")
        self.cbx1.addItem("")
        self.cbx1.addItem("")
        self.hlayout1_3.addWidget(self.cbx1)
        self.hlayout1_3.setStretch(1, 1)
        self.hlayout_3.addLayout(self.hlayout1_3)
        self.hlayout2_3 = QtWidgets.QHBoxLayout()
        self.hlayout2_3.setSpacing(0)
        self.hlayout2_3.setObjectName("hlayout2_3")
        self.lb2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb2.setObjectName("lb2")
        self.hlayout2_3.addWidget(self.lb2)
        self.cbx2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cbx2.setObjectName("cbx2")
        self.cbx2.addItem("")
        self.cbx2.addItem("")
        self.cbx2.addItem("")
        self.cbx2.addItem("")
        self.cbx2.addItem("")
        self.cbx2.addItem("")
        self.cbx2.addItem("")
        self.hlayout2_3.addWidget(self.cbx2)
        self.hlayout2_3.setStretch(1, 1)
        self.hlayout_3.addLayout(self.hlayout2_3)
        self.hlayout_3.setStretch(0, 1)
        self.hlayout_3.setStretch(1, 1)
        self.vlayout1_2.addLayout(self.hlayout_3)
        self.hlayout6_4 = QtWidgets.QHBoxLayout()
        self.hlayout6_4.setSpacing(100)
        self.hlayout6_4.setObjectName("hlayout6_4")
        self.btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn.setEnabled(True)
        self.btn.setObjectName("btn")
        self.hlayout6_4.addWidget(self.btn)
        self.vlayout1_2.addLayout(self.hlayout6_4)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(CompareDialog)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 100, 871, 411))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.hlayout4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.hlayout4.setContentsMargins(0, 0, 0, 0)
        self.hlayout4.setObjectName("hlayout4")
        self.wg1 = QtWidgets.QWidget(self.horizontalLayoutWidget_6)
        self.wg1.setObjectName("wg1")
        self.hlayout4.addWidget(self.wg1)
        self.wg2 = QtWidgets.QWidget(self.horizontalLayoutWidget_6)
        self.wg2.setObjectName("wg2")
        self.hlayout4.addWidget(self.wg2)
        self.wg3 = QtWidgets.QWidget(self.horizontalLayoutWidget_6)
        self.wg3.setObjectName("wg3")
        self.hlayout4.addWidget(self.wg3)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(CompareDialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 520, 261, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.hlayout5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.hlayout5.setContentsMargins(0, 0, 0, 0)
        self.hlayout5.setObjectName("hlayout5")
        self.lb4 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.lb4.setObjectName("lb4")
        self.hlayout5.addWidget(self.lb4)
        self.lb5 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.lb5.setFont(font)
        self.lb5.setObjectName("lb5")
        self.hlayout5.addWidget(self.lb5)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(CompareDialog)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(300, 520, 261, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.hlayout5_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.hlayout5_4.setContentsMargins(0, 0, 0, 0)
        self.hlayout5_4.setObjectName("hlayout5_4")
        self.lb4_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.lb4_4.setObjectName("lb4_4")
        self.hlayout5_4.addWidget(self.lb4_4)
        self.lb6 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.lb6.setFont(font)
        self.lb6.setObjectName("lb6")
        self.hlayout5_4.addWidget(self.lb6)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(CompareDialog)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(590, 520, 261, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.hlayout5_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.hlayout5_5.setContentsMargins(0, 0, 0, 0)
        self.hlayout5_5.setObjectName("hlayout5_5")
        self.lb4_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.lb4_5.setObjectName("lb4_5")
        self.hlayout5_5.addWidget(self.lb4_5)
        self.lb7 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.lb7.setFont(font)
        self.lb7.setObjectName("lb7")
        self.hlayout5_5.addWidget(self.lb7)

        self.retranslateUi(CompareDialog)
        QtCore.QMetaObject.connectSlotsByName(CompareDialog)

    def retranslateUi(self, CompareDialog):
        _translate = QtCore.QCoreApplication.translate
        CompareDialog.setWindowTitle(_translate("CompareDialog", "算法结果对比"))
        self.lb1.setText(_translate("CompareDialog", "主机："))
        self.cbx1.setItemText(0, _translate("CompareDialog", "选择master样品集"))
        self.cbx1.setItemText(1, _translate("CompareDialog", "m5spec"))
        self.cbx1.setItemText(2, _translate("CompareDialog", "mp5spec"))
        self.cbx1.setItemText(3, _translate("CompareDialog", "mp6spec"))
        self.cbx1.setItemText(4, _translate("CompareDialog", "m5nbs"))
        self.cbx1.setItemText(5, _translate("CompareDialog", "mp5nbs"))
        self.cbx1.setItemText(6, _translate("CompareDialog", "mp6nbs"))
        self.lb2.setText(_translate("CompareDialog", "目标机："))
        self.cbx2.setItemText(0, _translate("CompareDialog", "选择slaver样品集"))
        self.cbx2.setItemText(1, _translate("CompareDialog", "m5spec"))
        self.cbx2.setItemText(2, _translate("CompareDialog", "mp5spec"))
        self.cbx2.setItemText(3, _translate("CompareDialog", "mp6spec"))
        self.cbx2.setItemText(4, _translate("CompareDialog", "m5nbs"))
        self.cbx2.setItemText(5, _translate("CompareDialog", "mp5nbs"))
        self.cbx2.setItemText(6, _translate("CompareDialog", "mp6nbs"))
        self.btn.setText(_translate("CompareDialog", "三种传递算法预测结果比对"))
        self.lb4.setText(_translate("CompareDialog", "平均预测标准误差（SEP）："))
        self.lb5.setText(_translate("CompareDialog", "0.00"))
        self.lb4_4.setText(_translate("CompareDialog", "平均预测标准误差（SEP）："))
        self.lb6.setText(_translate("CompareDialog", "0.00"))
        self.lb4_5.setText(_translate("CompareDialog", "平均预测标准误差（SEP）："))
        self.lb7.setText(_translate("CompareDialog", "0.00"))

