# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dsUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DsDialog(object):
    def setupUi(self, DsDialog):
        DsDialog.setObjectName("DsDialog")
        DsDialog.resize(800, 600)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(DsDialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 520, 281, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.hlayout5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.hlayout5.setContentsMargins(0, 0, 0, 0)
        self.hlayout5.setObjectName("hlayout5")
        self.lb4 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.lb4.setObjectName("lb4")
        self.hlayout5.addWidget(self.lb4)
        self.lb5 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.lb5.setFont(font)
        self.lb5.setObjectName("lb5")
        self.hlayout5.addWidget(self.lb5)
        self.verticalLayoutWidget = QtWidgets.QWidget(DsDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 9, 771, 84))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vlayout1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vlayout1.setContentsMargins(0, 0, 0, 0)
        self.vlayout1.setObjectName("vlayout1")
        self.hlayout = QtWidgets.QHBoxLayout()
        self.hlayout.setSpacing(30)
        self.hlayout.setObjectName("hlayout")
        self.hlayout1 = QtWidgets.QHBoxLayout()
        self.hlayout1.setSpacing(6)
        self.hlayout1.setObjectName("hlayout1")
        self.lb1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb1.setObjectName("lb1")
        self.hlayout1.addWidget(self.lb1)
        self.cbx1 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cbx1.setObjectName("cbx1")
        self.cbx1.addItem("")
        self.cbx1.addItem("")
        self.cbx1.addItem("")
        self.cbx1.addItem("")
        self.cbx1.addItem("")
        self.cbx1.addItem("")
        self.cbx1.addItem("")
        self.hlayout1.addWidget(self.cbx1)
        self.hlayout1.setStretch(1, 1)
        self.hlayout.addLayout(self.hlayout1)
        self.hlayout2 = QtWidgets.QHBoxLayout()
        self.hlayout2.setSpacing(0)
        self.hlayout2.setObjectName("hlayout2")
        self.lb2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb2.setObjectName("lb2")
        self.hlayout2.addWidget(self.lb2)
        self.cbx2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cbx2.setObjectName("cbx2")
        self.cbx2.addItem("")
        self.cbx2.addItem("")
        self.cbx2.addItem("")
        self.cbx2.addItem("")
        self.cbx2.addItem("")
        self.cbx2.addItem("")
        self.cbx2.addItem("")
        self.hlayout2.addWidget(self.cbx2)
        self.hlayout2.setStretch(1, 1)
        self.hlayout.addLayout(self.hlayout2)
        self.hlayout3 = QtWidgets.QHBoxLayout()
        self.hlayout3.setObjectName("hlayout3")
        self.lb3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb3.setObjectName("lb3")
        self.hlayout3.addWidget(self.lb3)
        self.cbx3 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cbx3.setObjectName("cbx3")
        self.cbx3.addItem("")
        self.hlayout3.addWidget(self.cbx3)
        self.hlayout3.setStretch(1, 1)
        self.hlayout.addLayout(self.hlayout3)
        self.hlayout.setStretch(0, 1)
        self.hlayout.setStretch(1, 1)
        self.hlayout.setStretch(2, 1)
        self.vlayout1.addLayout(self.hlayout)
        self.hlayout6_3 = QtWidgets.QHBoxLayout()
        self.hlayout6_3.setSpacing(100)
        self.hlayout6_3.setObjectName("hlayout6_3")
        self.btn0 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn0.setObjectName("btn0")
        self.hlayout6_3.addWidget(self.btn0)
        self.btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn.setObjectName("btn")
        self.hlayout6_3.addWidget(self.btn)
        self.vlayout1.addLayout(self.hlayout6_3)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(DsDialog)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 560, 771, 31))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.hlayout6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.hlayout6.setContentsMargins(0, 0, 0, 0)
        self.hlayout6.setObjectName("hlayout6")
        self.btn1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.btn1.setObjectName("btn1")
        self.hlayout6.addWidget(self.btn1)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(DsDialog)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 100, 771, 411))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.hlayout4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.hlayout4.setContentsMargins(0, 0, 0, 0)
        self.hlayout4.setObjectName("hlayout4")
        self.wg = QtWidgets.QWidget(self.horizontalLayoutWidget_6)
        self.wg.setObjectName("wg")
        self.hlayout4.addWidget(self.wg)

        self.retranslateUi(DsDialog)
        QtCore.QMetaObject.connectSlotsByName(DsDialog)

    def retranslateUi(self, DsDialog):
        _translate = QtCore.QCoreApplication.translate
        DsDialog.setWindowTitle(_translate("DsDialog", "DS算法"))
        self.lb4.setText(_translate("DsDialog", "平均预测标准误差（SEP）："))
        self.lb5.setText(_translate("DsDialog", "0.00"))
        self.lb1.setText(_translate("DsDialog", "主机："))
        self.cbx1.setItemText(0, _translate("DsDialog", "选择master样品集"))
        self.cbx1.setItemText(1, _translate("DsDialog", "m5spec"))
        self.cbx1.setItemText(2, _translate("DsDialog", "mp5spec"))
        self.cbx1.setItemText(3, _translate("DsDialog", "mp6spec"))
        self.cbx1.setItemText(4, _translate("DsDialog", "m5nbs"))
        self.cbx1.setItemText(5, _translate("DsDialog", "mp5nbs"))
        self.cbx1.setItemText(6, _translate("DsDialog", "mp6nbs"))
        self.lb2.setText(_translate("DsDialog", "目标机："))
        self.cbx2.setItemText(0, _translate("DsDialog", "选择slaver样品集"))
        self.cbx2.setItemText(1, _translate("DsDialog", "m5spec"))
        self.cbx2.setItemText(2, _translate("DsDialog", "mp5spec"))
        self.cbx2.setItemText(3, _translate("DsDialog", "mp6spec"))
        self.cbx2.setItemText(4, _translate("DsDialog", "m5nbs"))
        self.cbx2.setItemText(5, _translate("DsDialog", "mp5nbs"))
        self.cbx2.setItemText(6, _translate("DsDialog", "mp6nbs"))
        self.lb3.setText(_translate("DsDialog", "样本数量："))
        self.cbx3.setItemText(0, _translate("DsDialog", "选择样本数量"))
        self.btn0.setText(_translate("DsDialog", "原光谱对比"))
        self.btn.setText(_translate("DsDialog", "DS预测结果"))
        self.btn1.setText(_translate("DsDialog", "样本数量与SEP关系图"))

