# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pdsUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PdsDialog(object):
    def setupUi(self, PdsDialog):
        PdsDialog.setObjectName("PdsDialog")
        PdsDialog.resize(800, 600)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(PdsDialog)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 560, 771, 31))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.hlayout6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.hlayout6.setContentsMargins(0, 0, 0, 0)
        self.hlayout6.setSpacing(40)
        self.hlayout6.setObjectName("hlayout6")
        self.btn1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.btn1.setObjectName("btn1")
        self.hlayout6.addWidget(self.btn1)
        self.btn2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.btn2.setObjectName("btn2")
        self.hlayout6.addWidget(self.btn2)
        self.btn3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.btn3.setObjectName("btn3")
        self.hlayout6.addWidget(self.btn3)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(PdsDialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 520, 281, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.hlayout5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.hlayout5.setContentsMargins(0, 0, 0, 0)
        self.hlayout5.setObjectName("hlayout5")
        self.lb4 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.lb4.setObjectName("lb4")
        self.hlayout5.addWidget(self.lb4)
        self.lb5 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.lb5.setFont(font)
        self.lb5.setObjectName("lb5")
        self.hlayout5.addWidget(self.lb5)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(PdsDialog)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 100, 771, 411))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.hlayout4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.hlayout4.setContentsMargins(0, 0, 0, 0)
        self.hlayout4.setObjectName("hlayout4")
        self.wg = QtWidgets.QWidget(self.horizontalLayoutWidget_6)
        self.wg.setObjectName("wg")
        self.hlayout4.addWidget(self.wg)
        self.verticalLayoutWidget = QtWidgets.QWidget(PdsDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 771, 90))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vlayout1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vlayout1.setContentsMargins(0, 0, 0, 0)
        self.vlayout1.setObjectName("vlayout1")
        self.hlayout = QtWidgets.QHBoxLayout()
        self.hlayout.setSpacing(200)
        self.hlayout.setObjectName("hlayout")
        self.hlayout1 = QtWidgets.QHBoxLayout()
        self.hlayout1.setSpacing(6)
        self.hlayout1.setObjectName("hlayout1")
        self.lb1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb1.setObjectName("lb1")
        self.hlayout1.addWidget(self.lb1)
        self.cbx1 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cbx1.setObjectName("cbx1")
        self.cbx1.addItem("")
        self.cbx1.addItem("")
        self.cbx1.addItem("")
        self.cbx1.addItem("")
        self.cbx1.addItem("")
        self.cbx1.addItem("")
        self.cbx1.addItem("")
        self.hlayout1.addWidget(self.cbx1)
        self.hlayout1.setStretch(1, 1)
        self.hlayout.addLayout(self.hlayout1)
        self.hlayout2 = QtWidgets.QHBoxLayout()
        self.hlayout2.setSpacing(0)
        self.hlayout2.setObjectName("hlayout2")
        self.lb2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb2.setObjectName("lb2")
        self.hlayout2.addWidget(self.lb2)
        self.cbx2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cbx2.setObjectName("cbx2")
        self.cbx2.addItem("")
        self.cbx2.addItem("")
        self.cbx2.addItem("")
        self.cbx2.addItem("")
        self.cbx2.addItem("")
        self.cbx2.addItem("")
        self.cbx2.addItem("")
        self.hlayout2.addWidget(self.cbx2)
        self.hlayout2.setStretch(1, 1)
        self.hlayout.addLayout(self.hlayout2)
        self.hlayout.setStretch(0, 1)
        self.hlayout.setStretch(1, 1)
        self.vlayout1.addLayout(self.hlayout)
        self.hlayout_2 = QtWidgets.QHBoxLayout()
        self.hlayout_2.setSpacing(50)
        self.hlayout_2.setObjectName("hlayout_2")
        self.hlayout3 = QtWidgets.QHBoxLayout()
        self.hlayout3.setObjectName("hlayout3")
        self.lb3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb3.setObjectName("lb3")
        self.hlayout3.addWidget(self.lb3)
        self.cbx3 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cbx3.setObjectName("cbx3")
        self.cbx3.addItem("")
        self.hlayout3.addWidget(self.cbx3)
        self.hlayout3.setStretch(1, 1)
        self.hlayout_2.addLayout(self.hlayout3)
        self.hlayout1_2 = QtWidgets.QHBoxLayout()
        self.hlayout1_2.setSpacing(6)
        self.hlayout1_2.setObjectName("hlayout1_2")
        self.lb1_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb1_2.setObjectName("lb1_2")
        self.hlayout1_2.addWidget(self.lb1_2)
        self.cbx4 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cbx4.setObjectName("cbx4")
        self.cbx4.addItem("")
        self.hlayout1_2.addWidget(self.cbx4)
        self.hlayout1_2.setStretch(1, 1)
        self.hlayout_2.addLayout(self.hlayout1_2)
        self.hlayout2_2 = QtWidgets.QHBoxLayout()
        self.hlayout2_2.setSpacing(20)
        self.hlayout2_2.setObjectName("hlayout2_2")
        self.cmpKBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.cmpKBtn.setObjectName("cmpKBtn")
        self.hlayout2_2.addWidget(self.cmpKBtn)
        self.cbx5 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cbx5.setObjectName("cbx5")
        self.cbx5.addItem("")
        self.hlayout2_2.addWidget(self.cbx5)
        self.hlayout2_2.setStretch(1, 1)
        self.hlayout_2.addLayout(self.hlayout2_2)
        self.vlayout1.addLayout(self.hlayout_2)
        self.hlayout6_2 = QtWidgets.QHBoxLayout()
        self.hlayout6_2.setSpacing(100)
        self.hlayout6_2.setObjectName("hlayout6_2")
        self.btn0 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn0.setObjectName("btn0")
        self.hlayout6_2.addWidget(self.btn0)
        self.btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn.setEnabled(True)
        self.btn.setObjectName("btn")
        self.hlayout6_2.addWidget(self.btn)
        self.vlayout1.addLayout(self.hlayout6_2)

        self.retranslateUi(PdsDialog)
        QtCore.QMetaObject.connectSlotsByName(PdsDialog)

    def retranslateUi(self, PdsDialog):
        _translate = QtCore.QCoreApplication.translate
        PdsDialog.setWindowTitle(_translate("PdsDialog", "PDS算法"))
        self.btn1.setText(_translate("PdsDialog", "样本数量与SEP关系图"))
        self.btn2.setText(_translate("PdsDialog", "窗口大小与SEP关系图"))
        self.btn3.setText(_translate("PdsDialog", "主成分数与SEP关系图"))
        self.lb4.setText(_translate("PdsDialog", "平均预测标准误差（SEP）："))
        self.lb5.setText(_translate("PdsDialog", "0.00"))
        self.lb1.setText(_translate("PdsDialog", "主机："))
        self.cbx1.setItemText(0, _translate("PdsDialog", "选择master样品集"))
        self.cbx1.setItemText(1, _translate("PdsDialog", "m5spec"))
        self.cbx1.setItemText(2, _translate("PdsDialog", "mp5spec"))
        self.cbx1.setItemText(3, _translate("PdsDialog", "mp6spec"))
        self.cbx1.setItemText(4, _translate("PdsDialog", "m5nbs"))
        self.cbx1.setItemText(5, _translate("PdsDialog", "mp5nbs"))
        self.cbx1.setItemText(6, _translate("PdsDialog", "mp6nbs"))
        self.lb2.setText(_translate("PdsDialog", "目标机："))
        self.cbx2.setItemText(0, _translate("PdsDialog", "选择slaver样品集"))
        self.cbx2.setItemText(1, _translate("PdsDialog", "m5spec"))
        self.cbx2.setItemText(2, _translate("PdsDialog", "mp5spec"))
        self.cbx2.setItemText(3, _translate("PdsDialog", "mp6spec"))
        self.cbx2.setItemText(4, _translate("PdsDialog", "m5nbs"))
        self.cbx2.setItemText(5, _translate("PdsDialog", "mp5nbs"))
        self.cbx2.setItemText(6, _translate("PdsDialog", "mp6nbs"))
        self.lb3.setText(_translate("PdsDialog", "样本数量："))
        self.cbx3.setItemText(0, _translate("PdsDialog", "选择样本数量"))
        self.lb1_2.setText(_translate("PdsDialog", "窗口大小:"))
        self.cbx4.setItemText(0, _translate("PdsDialog", "选择窗口大小"))
        self.cmpKBtn.setText(_translate("PdsDialog", "计算主成分数："))
        self.cbx5.setItemText(0, _translate("PdsDialog", "选择主成分数"))
        self.btn0.setText(_translate("PdsDialog", "原光谱对比"))
        self.btn.setText(_translate("PdsDialog", "PDS预测结果"))

