# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(825, 635)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 791, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.hlayout1 = QtWidgets.QHBoxLayout()
        self.hlayout1.setSpacing(30)
        self.hlayout1.setObjectName("hlayout1")
        self.btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn.setObjectName("btn")
        self.hlayout1.addWidget(self.btn)
        self.cbx = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cbx.setObjectName("cbx")
        self.hlayout1.addWidget(self.cbx)
        self.verticalLayout_3.addLayout(self.hlayout1)
        self.tw = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tw.setObjectName("tw")
        self.tw.setColumnCount(0)
        self.tw.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tw)
        self.hlayout2 = QtWidgets.QHBoxLayout()
        self.hlayout2.setObjectName("hlayout2")
        self.lb1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb1.setObjectName("lb1")
        self.hlayout2.addWidget(self.lb1)
        self.lb2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb2.setObjectName("lb2")
        self.hlayout2.addWidget(self.lb2)
        self.verticalLayout_3.addLayout(self.hlayout2)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 570, 791, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.hlayout4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.hlayout4.setContentsMargins(0, 0, 0, 0)
        self.hlayout4.setObjectName("hlayout4")
        self.btn1 = QtWidgets.QPushButton(self.layoutWidget)
        self.btn1.setObjectName("btn1")
        self.hlayout4.addWidget(self.btn1)
        self.btn2 = QtWidgets.QPushButton(self.layoutWidget)
        self.btn2.setObjectName("btn2")
        self.hlayout4.addWidget(self.btn2)
        self.btn3 = QtWidgets.QPushButton(self.layoutWidget)
        self.btn3.setObjectName("btn3")
        self.hlayout4.addWidget(self.btn3)
        self.compareBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.compareBtn.setObjectName("compareBtn")
        self.hlayout4.addWidget(self.compareBtn)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 260, 791, 291))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.hlayout3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.hlayout3.setContentsMargins(0, 0, 0, 0)
        self.hlayout3.setObjectName("hlayout3")
        self.wg1 = QtWidgets.QWidget(self.horizontalLayoutWidget_2)
        self.wg1.setObjectName("wg1")
        self.hlayout3.addWidget(self.wg1)
        self.wg2 = QtWidgets.QWidget(self.horizontalLayoutWidget_2)
        self.wg2.setEnabled(True)
        self.wg2.setObjectName("wg2")
        self.hlayout3.addWidget(self.wg2)
        self.layoutWidget.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.verticalLayoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "模型传递算法演示主界面"))
        self.btn.setText(_translate("MainWindow", "导入原始数据"))
        self.lb1.setText(_translate("MainWindow", "原始光谱"))
        self.lb2.setText(_translate("MainWindow", "中心光谱"))
        self.btn1.setText(_translate("MainWindow", "DS算法"))
        self.btn2.setText(_translate("MainWindow", "PDS算法"))
        self.btn3.setText(_translate("MainWindow", "Shenk\'s算法"))
        self.compareBtn.setText(_translate("MainWindow", "对比"))

